"""Update conversations schema with interaction and resolved

Revision ID: 4121871e38a9
Revises: c0527fe17ccd
Create Date: 2025-08-25 18:13:49.576001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4121871e38a9'
down_revision: Union[str, Sequence[str], None] = 'c0527fe17ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('interaction', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('conversations', sa.Column('resolved', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('conversations', 'start_time')
    op.drop_column('conversations', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'resolved')
    op.drop_column('conversations', 'interaction')
    # ### end Alembic commands ###
